import './style.css';
import contact from '../assets/Contact.jpg';
export default function History() {
    return (
        <section id = 'HistorySection'>
            <div style={{ backgroundImage: `url(${contact})`,opacity:'78%'}}>
                <h1>History:</h1>
                <p className='HistoryPara'>As the British East India Company expanded its purview in South Asia during the late 1700s, great numbers of its employees moved from England to carve out new lives for themselves in India. As they traveled through the country and encountered unusual flora and fauna, stunning ancient monuments, and exotic new people, they wanted to capture these images to send or take home. Whereas the modern tourist would rely on his camera for such a task, eighteenth- and nineteenth-century travelers had to hire Indian painters to do the job. The works produced by these artists, undertaken in a European style and palette, are known collectively as “Company” paintings. They are characterized in medium by the use of watercolors (instead of gouache), and in technique by the appearance of linear perspective and shading. Aesthetically, they are the descendants of the picturesque scenes of India created by the likes of Thomas and William Daniell.</p>
                <p className='HistoryPara'>This style of painting arose in a number of different cities. Work from each region is distinguishable by style, which grew out of and was heavily influenced by earlier local traditions. Calcutta was among the important early production centers, as the site of one of the oldest British trade houses. The city’s most enthusiastic patrons were Lord Impey, chief justice of the High Court from 1777 to 1783, and the Marquess Wellesley, who served as governor-general from 1798 to 1805. Both had collected large menageries and hired artists to paint each of the birds and animals in them. A Company-established botanical garden in Calcutta then undertook a similar project for the samples of plant life it had collected. Other influential painting centers were in Varanasi, a major Hindu pilgrimage site that drew many tourists (who knew it as Benares), and Madras, where Lord and Lady Clive were stationed from 1798 to 1804. Delhi’s market expanded after the city’s occupation by the British in 1803. Its magnificent Mughal monuments were the most popular subjects, and its artists were unique in using ivory as a base for painting. Other common subjects from this time were the residences, servants, carriages, horses, and other possessions that Company employees had amassed; Lady Impey was the patron of a number of such scenes.</p>
                <p className='HistoryPara'>While in the early phases of this school artists depended on a few key patrons, by the beginning of the nineteenth century, enterprising Indian artists had begun to create sets of standard popular subjects that could be sold to any tourist passing through the major attractions. Such sets might depict a range of monuments, festivals, castes, occupations, or costumes of the subcontinent.</p>
                <p className='HistoryPara'>Among the famous artists of the genre were Sewak Ram, who worked in Patna, and members of the Ghulam ‘Ali Khan family of Delhi. Patna was one of the major centers of Company painting because it was home to both an important factory and a Provincial Committee, and thus to many British expatriates. Ram seems to have moved there in the 1790s to find work; by the 1820s, his large-scale paintings of festivals and ceremonies were being collected by the likes of Lord Minto and Lord Amherst, both governors-general. When brothers William and James Fraser were sent by the Company in 1815–16 to tour newly conquered lands in the north of the country, they took artists from Delhi with them. It was probably at this time that Ghulam ‘Ali Khan made contact with them, but his known works date to after the Frasers’ return to Delhi in the 1820s. Khan is particularly noted for his scenes of village life; other members of the family were especially skilled at portraiture.
                    Such a style of painting did not develop throughout the country; other cities did not have the monuments to attract British tourists or, as in the case of Rajasthan, Hyderabad, and the Punjab Hills, were home to important local patrons. The school lost its momentum as photography was introduced to India in the early 1840s.</p>
            </div>
        </section>
    )
}